import type { Metadata } from "next";
import styles from "./layout.module.css"

export const metadata: Metadata = {
  title: "MedCare",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        {children}
      </body>
    </html>
  ); 
}
