import type { Metadata } from "next";
import styles from "./layout.module.css"
import type { Viewport } from 'next'
import Navbar from "./components/layouts/Navbar/Navbar";
import { AuthProvider } from "./context/authContext";

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}
export const metadata: Metadata = {
  title: "MedCare",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en" className={styles.html}>
        <body className={styles.body}>
          <Navbar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
